### ISSUE TITLE
Erro while building the App

### ISSUE THREAD

**Issue by gjimenezlr** [edudnyk/SheeKit#2]
Hi, I would like to use your library, followed all the instructions but I'm getting this compilation error:

![Screen Shot 2021-12-02 at 12 03 46 PM](https://user-images.githubusercontent.com/95256258/144478382-17101047-b51a-401c-b0bb-5508dea4f4aa.png)

I did a new empty project to test and is working fine, but I cannot get it to work in this other project.

Any suggestion?

**Comment by edudnyk** [comment]
Hi.
Please provide steps to reproduce the issue.

**Comment by gjimenezlr** [comment]
Hi, thank you for the quick response I did as you write in the read me

    Select your project in File Navigator, then select the project again on top of the list of targets. You'll see list of packages.
    Press ＋ button.
    In the appeared window, press ＋ button in the bottom left corner.
    In the appeared menu, select "Add Swift Package Collection"
    In the appeared dialog, enter package collection URL: https://swiftpackageindex.com/edudnyk/collection.json
    Press "Add Collection"
    Select SheeKit package from the collection.
    In Frameworks, Libraries, and Embedded Content section of your app target change 'SheeKit' package Embed option to Embed & Sign.

I have xcode 13, but the app have several build targets I'm not sure is that is causing the issue

**Comment by edudnyk** [comment]
Are you performing the last step from the list on the app target, not on some library or framework targets?

**Comment by gjimenezlr** [comment]
I'm do it in here.

![Screen Shot 2021-12-02 at 1 27 08 PM](https://user-images.githubusercontent.com/95256258/144489619-cdb3490f-aa6c-4095-a256-38de580c40c7.png)

**Comment by edudnyk** [comment]
Hard to tell what's going wrong, try cleaning / removing `~/Library/Developer/Xcode/DerivedData` folder. If does not help, try removing `.swiftpm` folder in your project root folder and then re-add the package. SwiftPM is still not perfect. Let me know if that helps, otherwise I will change the library into static to make things simpler.

**Comment by gjimenezlr** [comment]
No luck, I clean everything, and still gives the error.

**Comment by gjimenezlr** [comment]
@edudnyk Hi, I tested some others libraries, only having troubles with yours, is there something you can do about it please?

**Comment by edudnyk** [comment]
@gjimenezlr As I mentioned, SwiftPM is still not perfect. Please submit a bug report to apple about Swift Package Manager via http://feedbackassistant.apple.com/. I will release tomorrow the new major version of the package where you will not have to choose "Embed & Sing" for it.

**Comment by edudnyk** [comment]
In the meanwhile, if you are blocked by this issue, you can try setting up the library with CocoaPods.

**Comment by gjimenezlr** [comment]
Thank you very much, I'll wait for your release, I dont use pods.

**Comment by edudnyk** [comment]
Ready. Please try out v 1.0.0 and let me know if all good with the static library.
