### ISSUE TITLE
switch Toggle will adjust sheet from large to medium

### ISSUE THREAD

**Issue by jagodki** [edudnyk/SheeKit#3]
Hi,

first of all: thank you for this great project.
I discovered an issue I cannot explain me: I created a sheet with medium and large detent with the following code:
```swift
.shee(
isPresented: self.$sheet.isShowing,
presentationStyle: .formSheet(properties: SheetProperties(prefersEdgeAttachedInCompactHeight: true, prefersGrabberVisible: true, detents: [.medium(), .large()], largestUndimmedDetentIdentifier: .medium, prefersScrollingExpandsWhenScrolledToEdge: false)),
content: {self.sheetContent()}
)
```
I inserted some Toggles in a List to the sheet. If the sheet is pulled up to the large detent and I switch one toggle, the current detent of the sheet will immediately changed to medium. This does not happen with other controls like Buttons. Could this be a problem with Toggles because their toggle status has to be published and the whole view will be redrawn, i.e. the sheet will drawn in its start detent? Or could you imagine another reason for this behaviour?

Best regards,
Christoph

**Comment by edudnyk** [comment]
Mind the parameter and documentation for it:

```
    /// The identifier of the selected detent. When `nil` or the identifier is not found in detents, the sheet is displayed at the smallest detent.
    /// Default: `nil`
    public var selectedDetentIdentifier: Binding<UISheetPresentationController.Detent.Identifier?>? = nil
```

Since you don't provide the storage for `selectedDetentIdentifier`, the default value is always `nil`, which causes sheet to always use smallest detent upon re-rendering of the content.

**Comment by edudnyk** [comment]
But I can agree that it's a good addition to the library to handle that automatically in case when there is 2 and more supported detents but no binding is provided. I'll add the fix for this.

**Comment by jagodki** [comment]
As too often: had not reading the documentation carefully, sorry for that. Now I am using a state var for selectedDetentIdentifier and it works like a charm. Thank you for your advice 😀 

I also tried the new version but did not notice any new behaviour, when I do not provide a state var for the selectedDetentIdentifier, i.e. it is nil.

**Comment by edudnyk** [comment]
I haven't released the new version with the fix yet. Stay tuned 🙂
