### ISSUE TITLE
Cannot convert value of type 'Binding<UISheetPresentationController.Detent.Identifier>'

### ISSUE THREAD

**Issue by jtansley** [edudnyk/SheeKit#5]
Hello,

Thank you for this useful Swift package! I'm trying to integrate this into my project but I'm getting the following error:

<img width="1308" alt="Screen Shot 2022-02-09 at 10 53 00 AM" src="https://user-images.githubusercontent.com/1450277/153239652-4974216e-6f1d-4ada-9207-779d44968735.png">

`Cannot convert value of type 'Binding<UISheetPresentationController.Detent.Identifier>' to expected argument type 'Binding<UISheetPresentationController.Detent.Identifier?>'`

I have this variable set as follows:
`@State private var selectedDetentIdentifier = UISheetPresentationController.Detent.Identifier.medium`

Thanks for your time

**Comment by edudnyk** [comment]
Hi @jtansley.

As the error mentions, the type of the identifier has to be optional. In your case, it infers non-optional type.

To make it optional, define it this way:

```swift
@State private var selectedDetentIdentifier: UISheetPresentationController.Detent.Identifier? = .medium
```

**Comment by jtansley** [comment]
That worked, thank you and thanks again for the quick response!
